version: '3.4'
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - /mnt/hgfs/VMware_data/nexus-data:/nexus-data
    tty: true
    stdin_open: true
    restart_policy:
      condition: on-failure
      delay: 5s