version: '3.4'
services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    tty: true
    stdin_open: true
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    restart_policy:
      condition: on-failure
      delay: 5s
secrets:
  registry.password:
    file: ./auth/registry.password
  domain.crt:
    file: ./certs/registry.crt
  domain.key:
    file: ./certs/registry.key
  domain.group.crt:
    file: ./certs/registry.group.crt
  domain.group.key:
    file: ./certs/registry.group.key
configs:
  registry.conf:
    file: ./conf/registry.nginx.conf
  registry.group.conf:
    file: ./conf/registry.group.nginx.conf
  jenkins.conf:
    file: ./conf/jenkins.nginx.conf
  nexus.conf:
    file: ./conf/nexus.nginx.conf
  mysql.conf:
    file: ./conf/mysql.nginx.conf
  nginx.conf:
    file: ./conf/nginx.conf