version: '3.4'
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - /mnt/hgfs/VMware_data/nexus-data:/nexus-data
    environment:
      - SHOW_ADMIN_PASSWORD:true
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
#        condition: on-failure
        delay: 5s