version: '3.4'
services:
  jenkins:
    image: jenkinsci/blueocean:1.19.0
    volumes:
      - /mnt/hgfs/VMware_data/jenkins-data:/var/jenkins_home
#    environment:
#      - DOCKER_HOST=tcp://docker.idler.com:2376
#      - DOCKER_TLS_VERIFY=1
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    configs:
      - source: jenkins.log.conf
        target: /var/jenkins_home/log.properties
configs:
  jenkins.log.conf:
    file: ./conf/log.properties
secrets:
  ca.pem:
    file: ./certs/ca.pem
  cert.pem:
    file: ./certs/cert.pem
  key.pem:
    file: ./certs/key.pem
